### ISSUE TITLE
Advanced feed overlap

### ISSUE THREAD

**Issue by SamuraiAwesome** [epiccakeking/anaopsuserscript#5]
The advanced feed overlaps, preventing you from closing a topic. The Private Messages tab pushes the Bookmarks tab downward, hiding the "X".
![Screen Shot 2019-05-07 at 11 05 32 AM](https://user-images.githubusercontent.com/23420796/57314851-14657e80-70b8-11e9-87a7-81f637aba978.png)

**Comment by SamuraiAwesome** [comment]
Only happens on class pages

**Comment by epiccakeking** [comment]
This is something I will likely not fix until I can be sure flex will not break anything. I might make a workaround where the page tab and the tab after is half width though.

**Comment by epiccakeking** [comment]
Should be fixed now. Update the userscript to 2.9.6 and it should work.
